add code editor
developer-plus/vue-hbs-admin pull request #79
Opened 2022-05-01 14:28 UTC by hongl-1

### Description

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

close issue #38

2022-05-01 14:53 UTC, Hongbusi requested changes

2022-05-01 14:53 UTC, Hongbusi commented on src/views/demo/code-editor/index.vue
> +function onCodeChange(code: string) {}
这里可以 `console.log` 一下，不然存在没什么意义了

2022-05-01 14:53 UTC, Hongbusi commented on src/views/demo/code-editor/index.vue
> +  <page-wrapper title="code编辑器">
code 与编辑器之间可以添加一个空格

2022-05-01 14:55 UTC, Hongbusi commented
<img width="245" alt="image" src="https://user-images.githubusercontent.com/53554371/166151472-006588bd-c371-4bc7-942f-ac922fbceaa0.png">
需要删除中间的 issue，关联语法为：`close #id`

2022-05-01 14:56 UTC, Hongbusi commented
<img width="897" alt="image" src="https://user-images.githubusercontent.com/53554371/166151529-7e81b495-6694-49c9-b0f2-2f241e87465f.png">
顶部的标题可以加上 type。例如：`feat: add code editor`

2022-05-01 14:57 UTC, Hongbusi commented
文档记得安排一下～

2022-05-02 03:13 UTC, likui628 reviewed
建议导入 @types/codemirror，避免 could not find a declaration file warning

2022-05-02 03:13 UTC, likui628 commented on src/components/CodeEditor/src/CodeEditor.vue
> +import CodeMirror from 'codemirror/lib/codemirror'
import CodeMirror from 'codemirror'

2022-05-02 06:01 UTC, Hongbusi commented on src/components/CodeEditor/src/CodeEditor.vue
> +  <div class="code-mirror" :style="{width: widthComputed, height: heightComputed}">
`:style="getStyle"` 可以把 widthComputed，heightComputed 合并一下

2022-05-02 06:01 UTC, Hongbusi commented on src/views/demo/code-editor/index.vue
> +
结尾多余空行可以删除

2022-05-02 06:43 UTC, hongl-1 commented on src/views/demo/code-editor/index.vue
> +
OK 我改一下

2022-05-02 07:14 UTC, Hongbusi approved these changes

2022-05-02 07:14 UTC, merged