feat: user logout
developer-plus/vue-hbs-admin pull request #91
Opened 2022-05-03 13:09 UTC by likui628

### Description
1. 用户登出清空token和用户信息
2. 用户名和用户头像使用接口返回的数据
3. 本地缓存value封装在对象```{value}```,避免value值为undefined时JSON.parse报错

close #53

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

2022-05-03 13:19 UTC, Hongbusi requested changes

2022-05-03 13:19 UTC, Hongbusi commented on src/layouts/default/header/components/UserDropdown.vue
> +        <a-menu-item key="logout" @click="()=>user.logout()">
`() => user.logout()` 箭头左右添加空格

2022-05-03 13:19 UTC, Hongbusi commented on src/utils/cache.ts
>    }
``` js
  setCache(key, value) {
    if (value) {
     localStorage.setItem(key, JSON.stringify(value))
    }
  }

  getCache(key) {
    let value = localStorage.getItem(key)
    if (value) {
      value = JSON.parse(value)
      return value
    } 
  }
```

更建议采用这种方式

2022-05-03 15:30 UTC, alexzhang1030 commented on src/utils/cache.ts
>    }
顺便加一个退出反馈吧

2022-05-04 03:52 UTC, likui628 commented on src/utils/cache.ts
>    }
> 顺便加一个退出反馈吧

可以说具体点

2022-05-04 05:39 UTC, alexzhang1030 commented
可以在退出成功后随便给一个什么反馈都可以，例如一个 message.success，增强一下交互感

2022-05-04 05:52 UTC, likui628 commented
> 
退出之后直接会返回登录界面，本身就是交互了，你觉得呢

2022-05-04 06:01 UTC, Hongbusi commented
> 可以在退出成功后随便给一个什么反馈都可以，例如一个 message.success，增强一下交互感

这个可以有

2022-05-04 06:09 UTC, likui628 commented
> > 可以在退出成功后随便给一个什么反馈都可以，例如一个 message.success，增强一下交互感
> 
> 这个可以有

现在有封装了message组件吗，要不要先提个issue

2022-05-04 06:12 UTC, Hongbusi commented
没有，先直接用 antdv 的 message 吧

2022-05-04 07:51 UTC, Hongbusi reviewed
setCache 和 getCache 对 value 的操作要优化一下

2022-05-04 08:02 UTC, Hongbusi commented
``` js
 setCache(key: string, value: any) {
    if (value) {
      window.localStorage.setItem(key, JSON.stringify(value))
    }
    else {
      window.localStorage.removeItem(key)
    }
  }
```

在 utils 中通过 value 决定是 setItem 还是 removeItem，是不合适的，更建议在你需要移除 cache 的地方调用 removeCache 来实现删除。

2022-05-04 08:34 UTC, likui628 commented
> ```js
>  setCache(key: string, value: any) {
>     if (value) {
>       window.localStorage.setItem(key, JSON.stringify(value))
>     }
>     else {
>       window.localStorage.removeItem(key)
>     }
>   }
> ```
> 
> 在 utils 中通过 value 决定是 setItem 还是 removeItem，是不合适的，更建议在你需要移除 cache 的地方调用 removeCache 来实现删除。

我之前使用{value:xxx}，已经现在判断undefined是进行removeItem删除主要是防止以下问题：
1. 调用者如果没有判断value值是否为undefined就会在localStorage存储`key`:'undefined'
2. getCache时进行JSON.pase时就会有异常（value值为‘undefined’字符串）

2022-05-04 08:48 UTC, Hongbusi commented
在 `LocalCache` 类中的 4 个方法，是为了统一对保存复杂类型数据 localStorage 操作进行 JSON 处理。setCache 只关注 setItem 操作，getCache 只关注 getItem 操作...

你可以在退出登录的时候，直接调用 localCache.removeCache(token)，来实现删除操作，更合理一些，而不是修改 LocalCache 类的方法来实现。

不知道这样说，你可以理解不

2022-05-04 09:06 UTC, likui628 commented
> 在 `LocalCache` 类中的 4 个方法，是为了统一对保存复杂类型数据 localStorage 操作进行 JSON 处理。setCache 只关注 setItem 操作，getCache 只关注 getItem 操作...
> 
> 你可以在退出登录的时候，直接调用 localCache.removeCache(token)，来实现删除操作，更合理一些，而不是修改 LocalCache 类的方法来实现。
> 
> 不知道这样说，你可以理解不

我懂你的意思了，我上面说了，如果setCache进去了undefined值，getCache里调用JSON.parse会有异常，这种边界状态你觉得如何处理比较好。

2022-05-04 13:25 UTC, Hongbusi commented
setCache 的时候有一个 if 判断，如果是 undefined 就不会保存了

2022-05-05 00:41 UTC, likui628 commented
> setCache 的时候有一个 if 判断，如果是 undefined 就不会保存了

不保存是可以，如果之前有值就不能替换了。所以还对｛value：xx｝方式合适

2022-05-05 00:49 UTC, Hongbusi commented
当你需要把保存的值变成空的时候，就调用 removeCache。

为什么不用 { value: xxx } 的形式？

如果你在控制台查看存储在本地的数据，外层都包裹一个 { value: xxx }，你会不会很烦躁？

2022-05-05 01:17 UTC, Hongbusi approved these changes

2022-05-08 09:45 UTC, Hongbusi approved these changes

2022-05-08 09:45 UTC, merged